# Golang CircleCI 2.0 configuration file
#
# World API Project
# 
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ironarachne/world
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p test-results/gotest
      - run: go test -v ./... | go-junit-report > test-results/gotest/results.xml
      - codecov/upload:
          file: test-results/gotest/results.xml
      - store_test_results:
          path: test-results
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ironarachne/world
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: |
          cd cmd/worldapi
          cp -r ../../images .
          VERSION_TAG=`cat ../../VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          docker build -t ironarachne/worldapi:$VERSION_TAG -t ironarachne/worldapi:$GIT_TAG -t ironarachne/worldapi:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/worldapi:$VERSION_TAG
          docker push ironarachne/worldapi:$GIT_TAG
          docker push ironarachne/worldapi:latest

workflows:
  version: 2
  test-build-publish:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master
