# Golang CircleCI 2.0 configuration file
#
# World API Project
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  test:
    environment:
      CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ironarachne/world
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: go get -v -t -d ./...
      - run:
          name: Set up CodeClimate test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            go test -coverprofile c.out ./...
            ./cc-test-reporter after-build --exit-code $?
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ironarachne/world
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: |
          cd cmd/worldapi
          cp -r ../../images .
          VERSION_TAG=`cat ../../VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          docker build -t ironarachne/worldapi:$VERSION_TAG -t ironarachne/worldapi:$GIT_TAG -t ironarachne/worldapi:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/worldapi:$VERSION_TAG
          docker push ironarachne/worldapi:$GIT_TAG
          docker push ironarachne/worldapi:latest

workflows:
  version: 2
  test-build-publish:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: release
