# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ironarachne/world
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd cmd/worldapi
          VERSION_TAG=`cat VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          docker build -t ironarachne/worldapi:$VERSION_TAG -t ironarachne/worldapi:$GIT_TAG -t ironarachne/worldapi:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/worldapi:$VERSION_TAG
          docker push ironarachne/worldapi:$GIT_TAG
          docker push ironarachne/worldapi:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: master